### ISSUE TITLE
Recognizes the device, but is still set to mono output

### ISSUE THREAD

**Issue by Kilil** [imustafin/razer-nari-pulseaudio-profile#10]
I am using fedora 33, copied all of the files in their respective places and still getting only mono output

**Comment by imustafin** [comment]
Hi. Sorry for not responding sooner. Do you still have this problem? I'm not really familiar with the packaging details of pulseaudio on Fedora, maybe some verbose logs of pulseaudio can help us here.

**Comment by Kilil** [comment]
I fixed it on my own, sorry for the scare
