### ISSUE TITLE
XKB error when inserting the receiver

### ISSUE THREAD

**Issue by amithiel** [imustafin/razer-nari-pulseaudio-profile#11]
Hi there! I have used your configuration with sucess in several debian based distos, and worked pretty good.
I'm now testing Manjaro, i installed through AUR, and while it works 100%, everytime i plug the usb receiver, instantly this error comes up:

https://i.imgur.com/bAyYQZq.png

Can you help me figure out why keyboard as anything to do with this?

cheers

**Comment by imustafin** [comment]
Hi. I don't know what problem you have, sorry.

Maybe if you check the output of `libinput list-devices` you might find something like
```
Device:           Razer Razer Nari Consumer Control
...
Capabilities:     keyboard
```
and start from there.

Hope this helped

**Comment by imustafin** [comment]
I'll close this for now. Please feel free to reopen if needed.
