### ISSUE TITLE
Doesnt work since last pulseaudio update.

### ISSUE THREAD

**Issue by DexyStorm** [imustafin/razer-nari-pulseaudio-profile#13]
I would love to help you or do it myself, but I can't code 4 shit.

**Comment by imustafin** [comment]
Hi. Have you checked #12? Whar distro are you on? Which pulseaudio version do you have?

**Comment by DexyStorm** [comment]
Hi. Unfortunately today archlinux decided to kill itself and for the love of god I couldn't save it. So I got frustrated and wiped the drive. I will reinstall in a couple of days. I think that #12 is going to help me. Thanks!

**Comment by imustafin** [comment]
Okay, good luck then :)

I will close this for now, please reopen if #12 doesn't help you.
