### ISSUE TITLE
Broke withe pipewire

### ISSUE THREAD

**Issue by amithiel** [imustafin/razer-nari-pulseaudio-profile#19]
Hey brother!
I've been using this profile for so...so many time now, in all linux distros ranging from debian based to arch. Worked awesome everytime.
Now the issue is.. as distros start moving to pipewire, this no longer works.
I was using latest Pop!_OS, and after an update.. it just broke.
I'm now testing arch with latest gnome, and i can't get this to work anymore.
Do you happen to got this working in recent distros?
cheers

**Comment by imustafin** [comment]
Hi. Did you try the instructions from the PipeWire section of readme?
> ### PipeWire
> 
> If you use PipeWire and you see the default profiles (names like *Multichannel*)
> but not these profiles (names like *Game Output*, *Chat Output*), then
> you might need to change the udev rules.
> 
> In `91-pulseaudio-razer-nari.rules` change `PULSE_PROFILE_SET` to `ACP_PROFILE_SET`.

Can you also post the relevant package versions (pulseaudio, pipewire, etc.) so that I can compare with what I have?

**Comment by amithiel** [comment]
Man, i feel ashamed for not properly reading instructions. I totally missed it
it's working fine! cheers
