### ISSUE TITLE
Headset mic not shown in sound setting GUI

### ISSUE THREAD

**Issue by tdesroches** [imustafin/razer-nari-pulseaudio-profile#2]
Ubuntu 18.04

Hey this works really well, thanks for making this.

The only thing that is funny is that the mic no longer is shown in the settings menu so I can't adjust the sensitivity or switch the input source.
![image](https://user-images.githubusercontent.com/30838946/77768339-b9fb4680-7018-11ea-8d95-ef5b9d3abcd5.png)
![image](https://user-images.githubusercontent.com/30838946/77768399-cf707080-7018-11ea-96cc-bab16f33d4f0.png)

Everything works however.  Is this something you encountered or perhaps I've installed it wrong? I didn't build it I just copied the relevant files.

**Comment by tdesroches** [comment]
I seems to have fixed it.  I'm not an expert on Pulseaudio but changing auto profile to no in razer-nari-usb-audio.conf has made the input appear.

**Comment by mittwinter** [comment]
Thanks for documenting and sharing this fix! It helped me to get the mic on my Razer Nari Ultimate to work!
