### ISSUE TITLE
Game/Chat balance doesn't work with pulseeffects enabled.

### ISSUE THREAD

**Issue by stefmmm** [imustafin/razer-nari-pulseaudio-profile#21]
I'm using ZorinOS 16 (Ubuntu 20.04 based)
the chat/game balance breaks if i use pulseeffects.
the reason i want to use pulseeffects is so the headset doesn't sound like crap.
but i also find myself missing the game/chat balance on numerous occasions.
if i select my razer nari chat audio device in discord it doesn't actually seem to be going to the chat audio device but instead game until i disable pulseeffects
now to be honest idk if this is an issue with the profile or pulseeffects.

**Comment by imustafin** [comment]
Hi. I don't have any experience with pulseeffects.

What do you mean by "headset ... sound like crap"? With my setup it is kinda ok (but maybe I just don't know how good headsets sound like :smile:)

By balance you mean the L/R balance? I haven't noticed such problems but I will try to recheck later.

> until i disable pulseeffects

This looks like a misconfiguration somewhere to me.

We can keep this issue open in case anyone faced similar problems.

**Comment by stefmmm** [comment]
Hi, I was able to solve this issue by adding 'WEBRTC VoiceEngine' (which is what discord uses) to the blacklist in pulse effects, i also modified the profile to exclude the chat-input from the output configuration, which probably didn't do much in my case but it's still something i modified.
By balance i mean the chat/game wheel on the left side of the headset.
and yeah it might just be personal preference but i find that lowering certain frequencies on the headset make it sound better.

**Comment by imustafin** [comment]
I had an impression that the balance wheel is 100% hardware :thinking: 

Anyways, glad you managed to fix the problem!
