### ISSUE TITLE
Doesnt work since last pulseaudio update.

### ISSUE THREAD

**Issue by DexyStorm** [imustafin/razer-nari-pulseaudio-profile#5]
Doesnt work since last pulseaudio update. The headphones dont show up in PulseAudio Volume Control. Please send help. Installed with yay through the AUR.

**Comment by imustafin** [comment]
Hi @DexyStorm. Which version do you have? Please show output of
```
pacman -Qvi pavucontrol pulseaudio
```

**Comment by DexyStorm** [comment]
Hello @imustafin. Here is the output:

Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : pavucontrol  pulseaudio
Name            : pavucontrol
Version         : 1:4.0-2
Description     : PulseAudio Volume Control
Architecture    : x86_64
URL             : https://freedesktop.org/software/pulseaudio/pavucontrol/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : libcanberra-pulse  gtkmm3  libsigc++
Optional Deps   : pulseaudio: Audio backend [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 931.42 KiB
Packager        : Evangelos Foutras <evangelos@foutrelis.com>
Build Date      : Tue 19 May 2020 10:59:22 AM CEST
Install Date    : Tue 23 Jun 2020 06:23:22 AM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

Name            : pulseaudio
Version         : 13.99.2+7+g6101798c7-2
Description     : A featureful, general-purpose sound server
Architecture    : x86_64
URL             : https://www.freedesktop.org/wiki/Software/PulseAudio/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : libpulse=13.99.2+7+g6101798c7-2  alsa-card-profiles  rtkit  libltdl  speexdsp  tdb  orc  libsoxr  webrtc-audio-processing
Optional Deps   : pulseaudio-alsa: ALSA configuration (recommended) [installed]
                  pulseaudio-zeroconf: Zeroconf support
                  pulseaudio-lirc: IR (lirc) support
                  pulseaudio-jack: Jack support
                  pulseaudio-bluetooth: Bluetooth support
                  pulseaudio-equalizer: Graphical equalizer
                  pulseaudio-rtp: RTP and RAOP support
Required By     : glava  plasma-pa  pulseaudio-alsa  pulseaudio-equalizer-ladspa  razer-nari-pulseaudio-profile
Optional For    : dolphin-emu  firefox  pavucontrol  phonon-qt5  phonon-qt5-gstreamer
Conflicts With  : None
Replaces        : pulseaudio-xen<=9.0  pulseaudio-gconf<=11.1
Installed Size  : 6.05 MiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Thu 08 Oct 2020 02:11:26 AM CEST
Install Date    : Sat 10 Oct 2020 12:39:31 PM CEST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : Signature

**Comment by imustafin** [comment]
I've also updated my system to this version and I have the same problem. Checking what can be done....

**Comment by imustafin** [comment]
Some strange things going on in the Arch pulseaudio packge (https://github.com/archlinux/svntogit-packages/commit/0fe4dfb7d8041587d8b03030037398a303aaa603). @nzbr maybe you could help us with the AUR package? Maybe after this update in `pulseaudio` with the new package `alsa-card-profiles`, we need to copy the profile config to a different directory in Arch.

@DexyStorm can you please check that
```
cp razer-nari-usb-audio.conf /usr/share/alsa-card-profile/mixer/profile-sets/
```
fixes the problem?

**Comment by DexyStorm** [comment]
Ayeee it fixed it. thanks :)

**Comment by imustafin** [comment]
Great. I'll update the readme. @nzbr if you are interested in updating the AUR package, please make a separate issue for this and we can discuss.

**Comment by theFra985** [comment]
Sorry but the new update broke my installation. I copied the `razer-nari-usb-audio.conf` back to the previous place and now it works.

Here is my output for `pacman -Qvi pavucontrol pulseaudio`:
```
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : pavucontrol  pulseaudio
Name            : pavucontrol
Version         : 1:4.0-2
Description     : PulseAudio Volume Control
Architecture    : x86_64
URL             : https://freedesktop.org/software/pulseaudio/pavucontrol/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : libcanberra-pulse  gtkmm3  libsigc++
Optional Deps   : pulseaudio: Audio backend [installed]
Required By     : None
Optional For    : manjaro-pulse
Conflicts With  : None
Replaces        : None
Installed Size  : 931,42 KiB
Packager        : Evangelos Foutras <evangelos@foutrelis.com>
Build Date      : mar 19 mag 2020, 10:59:22
Install Date    : dom 31 mag 2020, 14:17:03
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

Name            : pulseaudio
Version         : 13.0-3
Description     : A featureful, general-purpose sound server
Architecture    : x86_64
URL             : https://www.freedesktop.org/wiki/Software/PulseAudio/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : libpulse=13.0-3  rtkit  libltdl  speexdsp  tdb  orc  libsoxr  webrtc-audio-processing
Optional Deps   : pulseaudio-alsa: ALSA configuration (recommended) [installed]
Required By     : manjaro-pulse  plasma-pa  pulseaudio-alsa  pulseaudio-bluetooth  pulseaudio-ctl  pulseaudio-equalizer  pulseaudio-equalizer-ladspa  pulseaudio-jack  pulseaudio-lirc
                  pulseaudio-zeroconf  razer-nari-pulseaudio-profile
Optional For    : firefox  lib32-fluidsynth  pavucontrol  phonon-qt5  phonon-qt5-gstreamer
Conflicts With  : None
Replaces        : pulseaudio-xen<=9.0  pulseaudio-gconf<=11.1
Installed Size  : 6,24 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : sab 11 gen 2020, 19:25:37
Install Date    : mer 11 mar 2020, 14:47:34
Install Reason  : Installed as a dependency for another package
Install Script  : Yes
Validated By    : Signature
```

**Comment by imustafin** [comment]
@theFra985 please see #7
