### ISSUE TITLE
Fix AUR package for new pulseaudio version

### ISSUE THREAD

**Issue by nzbr** [imustafin/razer-nari-pulseaudio-profile#7]
The AUR package should be fixed now (see #5)
It would be great if someone could test it, as I don't have my Razer Nari with me right now

**Comment by nzbr** [comment]
cc @DexyStorm

**Comment by DexyStorm** [comment]
Doesnt work. Had to do 
cp razer-nari-usb-audio.conf /usr/share/alsa-card-profile/mixer/profile-sets/
after reinstalling the AUR package with yay

**Comment by nzbr** [comment]
Oh, I made a mistake in the path name. Just pushed a fixed version

**Comment by cristianghsandu** [comment]
For me the reverse happens, I need to copy the config file to /usr/share/pulseaudio/alsa-mixer/profile-sets/ for it to work again. I am on Manjaro.
It had stopped working when I updated the AUR package the other day.

**Comment by imustafin** [comment]
@cristianghsandu can you show the output of 
```
pacman -Qvi pulseaudio
```
And maybe
```
pacman -Qvi alsa-card-profiles
```

**Comment by cristianghsandu** [comment]
pacman -Qvi pulseaudio

Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : pulseaudio
Name            : pulseaudio
Version         : 13.0-3
Description     : A featureful, general-purpose sound server
Architecture    : x86_64
URL             : https://www.freedesktop.org/wiki/Software/PulseAudio/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : libpulse=13.0-3  rtkit  libltdl  speexdsp  tdb  orc  libsoxr  webrtc-audio-processing
Optional Deps   : pulseaudio-alsa: ALSA configuration (recommended) [installed]
Required By     : manjaro-pulse  pulseaudio-alsa  pulseaudio-bluetooth  pulseaudio-ctl  pulseaudio-equalizer  pulseaudio-jack  pulseaudio-lirc  pulseaudio-zeroconf  razer-nari-pulseaudio-profile
Optional For    : firefox  firefox-developer-edition  lib32-fluidsynth  pavucontrol  speech-dispatcher
Conflicts With  : None
Replaces        : pulseaudio-xen<=9.0  pulseaudio-gconf<=11.1
Installed Size  : 6,24 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Sb 11 ian 2020 20:25:37 +0200
Install Date    : Lu 11 mai 2020 19:04:12 +0300
Install Reason  : Installed as a dependency for another package
Install Script  : Yes
Validated By    : Signature

pacman -Qvi alsa-card-profiles

Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : alsa-card-profiles
error: package 'alsa-card-profiles' was not found

**Comment by imustafin** [comment]
@cristianghsandu thanks. I see that your version is `13.0-3`. This AUR update is needed only for `pulseaudio >= 13.99.2+7+g6101798c7-1`.

Have you been updating only some of the packages instead of doing full system upgrades :smiley:? Probably you should not do this (https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported). I guess now you should either upgrade `pulseaudio` or keep the previous version of `razer-nari-pulseaudio-profile`.

@nzbr I was thinking about this problem. I'm not experienced in maintaining AUR packages, but maybe make the AUR package depend on this updated version to disallow such breaking installs?

**Comment by imustafin** [comment]
I see. Sorry for this then 😳
> Have you been updating only some of the packages instead of doing full system upgrades :smiley: ?

I'm not sure if installing to both dirs is the best solution but is still a solution.

**Comment by nzbr** [comment]
New version is pushed

**Comment by cristianghsandu** [comment]
Updated package seeems to place the file in the right folder for me (/usr/share/pulseaudio/alsa-mixer/profile-sets/razer-nari-usb-audio.conf )

**Comment by imustafin** [comment]
@nzbr I think we also need to move the paths `/usr/share/pulseaudio/alsa-mixer/paths` to this new alsa-card-profile dir `/usr/share/alsa-card-profile/mixer/paths`.

We have just merged #8 but it was not working on my Arch machine. Paths seem to be loaded also from the `alsa-card-profile` subdir.

To test if everything is correct:
```
pactl list cards | grep razer-nari-output-game:
```
If paths are loaded correctly, it should give the correct name, type and priority (bold by me):
<pre>
razer-nari-output-game: <b>Game Output (type: Headset, priority: 9900</b>, latency offset: 0 usec)
</pre>

If paths were not loaded correctly, it will fallback to the default values (bold by me):
<pre>
razer-nari-output-game: <b>razer-nari-output-game (type: Unknown, priority: 0</b>, latency offset: 0 usec)
</pre>

**Comment by nzbr** [comment]
I pushed a new version here: https://git.nzbr.de/nzbr/razer-nari-pulseaudio-profile.aur
Can someone confirm that it works? If it does I will push it to the AUR

**Comment by mlowijs** [comment]
Just tested it and works fine on my installation!

**Comment by nzbr** [comment]
Just pushed the update. Feel free to reopen this issue if there are problems with it
